services:
  - type: web
    name: iara-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://iara-yrdx.onrender.com,https://iara-eight.vercel.app,https://iara-h5jp7meps-iara3.vercel.app
      - key: ADMIN_USER
        value: iara
      - key: ADMIN_PASS
        value: pulseras2026
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_7HOeMptSdmY5@ep-wandering-breeze-adetvf8t-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    autoDeploy: true
    branch: main
    repo: https://github.com/bonggiocrack-stack/IARA.git
