services:
  - type: web
    name: iara-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend/src && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://iara-yrdx.onrender.com,https://iara-eight.vercel.app
      - key: RENDER_DOCKERFILE
        value: "false"
    autoDeploy: true
    branch: main
    repo: https://github.com/bonggiocrack-stack/IARA.git
